name: 'Telegit'
description: 'Connect your GitHub Repo to Telegram'
author: 'athul'
inputs: 
  chat:
    description: 'Chat to send: chat id or @channel_name'
    required: true
  token:
    description: 'Telegram Bot token'
    required: true
  status:
    description: 'Job status'
    required: true
  stargazers:
    description: 'Get Stars of the Repo'
    default: ${{ github.event.repository.stargazers_count }}
  forkers:
    description: 'Number of Forks'
    default: ${{ github.event.repository.forks_count }}
  iu_title: 
    description: 'Issue Title'
    default: ${{ github.event.issue.title }}
  iu_num:
    description: 'Issue Number'
    default: ${{ github.event.issue.number }}
  iu_actor: 
    description: 'Issue Triggerer'
    default: ${{ github.event.issue.user.login }}
  iu_body:
    description: 'Issue Body'
    default: ${{ github.event.issue.body }}
  iu_com:
    description: 'Issue Comment'
    default: ${{github.event.comment.body}}
  pr_state:
    description: 'State of the PR'
    default: ${{ github.event.action }}
  pr_num:
    description: 'PR Number'
    default: ${{ github.event.number }}
  pr_title:
    description: 'Title of the PR'
    default: ${{ github.event.pull_request.title }}
  pr_body:
    description: 'Body/Contents of the PR'
    default: ${{ github.event.pull_request.body }}
  pr_base_ref:
    description: 'Target branch of merged PR'
    default: ${{ github.event.pull_request.base.ref }}
  pr_head_ref:
    description: 'Merging branch of PR'
    default: ${{ github.event.pull_request.head.ref }}
  pr_changed_files:
    description: 'Count of changed files in PR'
    default: ${{ github.event.pull_request.changed_files }}
  pr_requested_reviewers:
    description: 'Requested reviews'
    default: ${{ toJSON(github.event.pull_request.requested_reviewers) }}
  pr_url:
    description: 'Link to PR'
    default: ${{ github.event.pull_request.html_url }}
  pr_merged:
    description: 'Merged'
    default: ${{ github.event.pull_request.merged }}
  pr_merged_by:
    description: 'Merged by User'
    default: ${{ github.event.pull_request.merged_by.login }}
  push_commits:
    description: 'Push commits'
    default: ${{ toJSON(github.event.commits) }}
  push_compare_url:
    description: 'Compare url'
    default: ${{ github.event.compare }}
  push_author:
    description: 'Pusher'
    default: ${{ github.event.pusher.name }}
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: 'repeat'  
  color: 'green'